### ISSUE TITLE
"Fatal Error: Unknown Method" when computing coupling matrices on BNL Astro

### ISSUE THREAD

**Issue by msyriac** [damonge/NaMaster#12]
I've only been able to reproduce this on the BNL Astro Cluster and in the `unit_tests` branch. It happens during:

```
w00.compute_coupling_matrix(f0,f0,b)
```

in `tests/sample_flat.py`.

There is no traceback, just the error message followed by a random number:

```
 Fatal error: Unknown method -262427472
```

Some more info:
```
$ uname -a
Linux astro0010.rcf.bnl.gov 2.6.32-358.18.1.el6.x86_64 #1 SMP Tue Aug 27 14:23:09 CDT 2013 x86_64 x86_64 x86_64 GNU/Linux
$ gcc --version
gcc (GCC) 4.9.2
$ python
Python 2.7.5 (default, Oct 15 2013, 10:33:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
```

**Comment by damonge** [comment]
@msyriac I know we talked about this offline, but has this been resolved? If you wanna give it a try, the `validation` branch should be the more robust and up-to-date version of the code. It will hopefully be merged with master soon anyway...

**Comment by msyriac** [comment]
This hasn't been resolved, but due to completely unrelated issues around my BNL environment. I'll close it for now and re-open if I can pin it down better.
