### ISSUE TITLE
Bias B-mode spectrum depedence over r

### ISSUE THREAD

**Issue by Sylk1-9** [damonge/NaMaster#15]
Hi, 

I played a little with your code, more particularly with the sample_pureB.py script,  and found a strange behaviour the pure spectrum obtained : 
- I used NaMaster for python on three resolutions maps : nside=8, nside=16, and nside=32. 
- I choose a mask that keep 70% of the sky, only CMB maps, no noise added.
- I used four fiducial models with a tensor-to-scalar ratio of r=0.1, r=0.001, and r=0.0.
- Mask is apodised using an apodisation lenght=20.0, and an apotype='C1'.
![probl_nama_mask32](https://user-images.githubusercontent.com/25033218/37858348-f2dc3dcc-2f03-11e8-9796-525b29811d52.png)

I compute the spectrum for 200 simulations and choose to purify the B-modes. 
**_I get that the BB spectrum is more and more biased as the 'r' parameter tends to zero._**

Pictures are better than a long speech. I divided the error-bars by the square-root of the number of simulations : 

![probl_nama_r0 1](https://user-images.githubusercontent.com/25033218/37851737-55c74f86-2ee0-11e8-8146-3359e6cdaba6.png)
![probl_nama_r0 001](https://user-images.githubusercontent.com/25033218/37851739-562f6c4c-2ee0-11e8-9bbc-b93176c2ae74.png)
![probl_nama_r0 0](https://user-images.githubusercontent.com/25033218/37851736-55966c5e-2ee0-11e8-95a3-f2b699b4fa1d.png)

**The problem disappears when putting EE and TE to 0 :**
![probl_nama_noeer0 001](https://user-images.githubusercontent.com/25033218/37858239-aff74994-2f02-11e8-948e-dd2578de2027.png)
![probl_nama_noeer0 0](https://user-images.githubusercontent.com/25033218/37858238-afc4f994-2f02-11e8-833e-a86b15d155f4.png)

I don't know yet where exactly does this problem comes from. But I wanted to contact you anyway. Maybe you have a better idea than me. We could also discuss about it.

Best regards, and thank you for this package,

Sylvain

**Comment by damonge** [comment]
Hi @Sylk1-9 ,

thanks a lot for giving NaMaster a try. I'm 90% sure the issues you're seeing are related to the non-differentiable nature of the apodised mask you're using. The pure-B estimator needs a mask with well-defined second derivatives, and you can see that this is not the case given the boxy features in the mask. You can check how the second derivatives look by doing something like:

``
larr=np.arange(3*nside)
alm_mask=hp.map2alm(mask)
_,maskD2Q,maskD2U=hp.alm2map([np.zeros_like(alm_mask),hp.almxfl(alm_mask,np.sqrt((larr+2)*(larr+1)*larr*(larr-1))),np.zeros_like(alm_mask)],nside,pol=True)

hp.mollview(maskD2Q,max=200);
plt.show()
``

You'll probably see a very noisy map with weird features all over the place. Any numerical mask will usually have relatively noisy derivatives, and it should not introduce a huge bias in general. However the mask you're using is very evidently not differentiable. There are a couple of tricks you can play to get a nice differentiable mask:
1. Define the mask at a high resolution, making sure that it has nice, smooth edges there before apodizing and down-grading. Smoothing the mask (with healpy's 'smoothing' function) a bit before apodizing can also help.
2. Using an analytical mask that you know is completely differentiable. You can see some examples in this very nice paper: https://arxiv.org/abs/0903.2350

Let me know if this helps!

**Comment by damonge** [comment]
@Sylk1-9 : from your nice paper I imagine this has been solved ;-), so I'll close this.

**Comment by Sylk1-9** [comment]
Hi, 

thank you a lot for your response, your comment helped me a lot.
The mask second derivative had indeed weird features all over the place. Due to the mask shape, and too small apodization lenghts, the bias was still there at the first multipoles.
Longer apodization lengths or pre-smoohting permits to reduce this bias, but at the cost of variance increase for the remaining  multipoles due to the induced sky fraction reduction. 
A compromise must therefore be found. But I guess than rather than working on the apodization lenght,  the contour of the mask itself can be optimized in order to avoid those second derivative 'weird feature' .

Cheers, 

Sylvain
