### ISSUE TITLE
NaMaster paper: validating LSS-like power spectra in the full sky

### ISSUE THREAD

**Issue by damonge** [damonge/NaMaster#17]
Procedure to do this:
 - Change to the 'validation' branch and install the code.
 - Go to sandbox_validation/data. Executing the script get_validation_data.sh will generate all the masks and contaminant templates. You can regenerate this with different resolutions by running the script with different values for nside_LSS.
 - Once the data has been generated, go back to sandbox_validation and make use of check_sph.py to generate the validation data. Run `python check_sph.py -h` to see all available options. Note that the full batch of simulations can be split into segments for parallelization.

We will want to test the code for a large number of sims (O(1000)) for an nside=1024 if possible, and at least with mask, contaminants and varnoise. Aposize can be left as 0, but could also check results for 0.1 if we have time.

**Comment by fjaviersanchez** [comment]
This is the relative difference between input and output power spectrum divided  by the error from the dispersion (divided by the number of realizations, in this case 1000) with aposize=0.0 and Nside=1024

[cl_bias_1024.pdf](https://github.com/damonge/NaMaster/files/2159941/cl_bias_1024.pdf)

**Comment by damonge** [comment]
@fjaviersanchez : can you post a version of this with ell limited to [0,2*Nside]?

**Comment by fjaviersanchez** [comment]
Here:

![image](https://user-images.githubusercontent.com/13971732/42248422-3c8d44c2-7eda-11e8-8c13-f94d2f078972.png)

**Comment by fjaviersanchez** [comment]
And when no deprojection is done:

![image](https://user-images.githubusercontent.com/13971732/42248593-3a160124-7edb-11e8-982d-8e403351cf9d.png)

**Comment by fjaviersanchez** [comment]
![image](https://user-images.githubusercontent.com/13971732/42251146-5dc39f14-7eea-11e8-9359-8702245360ec.png)

This is the distribution of chi^{2} for the galaxy-galaxy power-spectra. I computed it as sum((cl_00-cl_00_th)**2/delta_cl_00**2) for each simulation. Then I normalized the histogram and overlaid a chi^2 distribution with the corresponding number of degrees of freedom (in this case it is 681)

**Comment by fjaviersanchez** [comment]
![image](https://user-images.githubusercontent.com/13971732/42253675-a60a2786-7ef7-11e8-9bba-5d6a8a0f79bc.png)

Same plot using the covariance instead of using only the diagonal errors. I also overlay a Gaussian (green line) with mean equal to the number of degrees of freedom and variance equal to the square root of the number of sims.

**Comment by damonge** [comment]
This is actually great and we should put it in the paper, but first we need to understand why the distribution doesn't match when you include the covariance matrix.

From the plot it seems like ndof~650, in which case, since we only have 1000 simulations, the covariance matrix would be super noisy. I see three options:
1. Use just the diagonal errors if we can convince ourselves that there are no significant correlations.
2. Correct the inverse covariance matrix by the Hartlap factor and see if that makes things match.
3. Run 10x more simulations. I'm guessing we don't want to do this ;-)

**Comment by fjaviersanchez** [comment]
After ~8 hours of running with 64 cores on Cori, I finished running 10 realizations of Nside=4096. It looks good so far. We, however, need more sims if we want to use this.

![image](https://user-images.githubusercontent.com/13971732/42353609-6c260258-8076-11e8-9e73-d0bae95a7eed.png)

And the correlation matrix:

![image](https://user-images.githubusercontent.com/13971732/42353615-7a3aa326-8076-11e8-96fe-90ea06b79d85.png)

**Comment by fjaviersanchez** [comment]
Same for 100 sims:

![image](https://user-images.githubusercontent.com/13971732/42475151-cfab82ca-8397-11e8-9511-4bc71dcf8e86.png)

![image](https://user-images.githubusercontent.com/13971732/42475159-d62a1cba-8397-11e8-99b6-4a01ac8a9044.png)

**Comment by damonge** [comment]
Copying latest results by @fjaviersanchez , which solve this issue:
![val_cl_lss_sph](https://user-images.githubusercontent.com/8809493/43363500-18c3b12e-92fe-11e8-8009-166962fae32e.png)
![val_chi2_lss_sph](https://user-images.githubusercontent.com/8809493/43363501-1b31f812-92fe-11e8-8552-812946805041.png)
