### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by DanielLenz** [damonge/NaMaster#25]
Did you happen to add python 3 support? I can't find the library file:

```ipython

In [1]: import pymaster
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-1e90212a3325> in <module>()
----> 1 import pymaster

~/anaconda/lib/python3.6/site-packages/pymaster/__init__.py in <module>()
     37
     38 """
---> 39 import nmtlib as lib
     40 import numpy as np
     41 from utils import mask_apodization, mask_apodization_flat, synfast_spherical, synfast_flat

ModuleNotFoundError: No module named 'nmtlib'
```

I remember that being an old issue, did you have the chance to look more into this or do you have any pointers? I'd be happy to dig some more as well, would be good to support python 3, now that many packages are dropping the support for 2.

**Comment by damonge** [comment]
@DanielLenz Right, I still haven't worked on making sure that python3 is supported, unfortunately. That's high in the priority list, so thanks a lot for opening this. I'll keep you posted with progress (hopefully soon).

**Comment by damonge** [comment]
OK, that was quick. @DanielLenz : I think the branch `python3` should be python-3-compatible. If you have time to check that it works for you, I'll merge with master and owe you a beer next time we're in the same city.

**Comment by DanielLenz** [comment]
Woah, that was really fast! I rather think I owe you one, but I'm certainly not complaining!

I can find the library file now, but run into the following:

```bash
ImportError: dlopen(/Users/dlenz/anaconda/lib/python3.6/site-packages/_nmtlib.cpython-36m-darwin.so, 2): Symbol not found: _nmt_compute_gaussian_covariance_flat
  Referenced from: /Users/dlenz/anaconda/lib/python3.6/site-packages/_nmtlib.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/dlenz/anaconda/lib/python3.6/site-packages/_nmtlib.cpython-36m-darwin.so
```

**Comment by DanielLenz** [comment]
Thanks, will look into this! On a related note, it might also make sense to set up tests for python and to integrate this into travis.

Making software widely available for a larger community with different operating systems, compilers, library version etc. is rather impossible without that.
